version: "3.9"
services:
  chrome:
    init: true
    image: haos616/chrome-headless-service:${PROJECT_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: live
    ports:
      - "127.0.0.1:8000:8000"
